name: proequity
description: "A new Flutter project."
version: 1.0.4

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get_it: ^7.6.7
  hive_flutter: ^1.1.0
  provider: ^6.1.2
  path_provider: ^2.1.2
  path: ^1.8.3
  image_picker: ^1.0.7
  permission_handler: ^11.2.0
  icons_plus: ^5.0.0
#  unique_identifier: ^0.3.0
  flutter_launcher_icons: ^0.13.1
  easy_splash_screen: ^1.0.4
  http: ^1.2.0
  fluttertoast: ^8.2.4
  panara_dialogs: ^0.1.4
  sqflite: ^2.3.2
  dropdown_search: ^5.0.6
  url_launcher: ^6.2.4
  flutter_easyloading: ^3.0.5
  geolocator: ^11.0.0
  custom_sliding_segmented_control: ^1.8.1
  flutter_image_compress: ^2.1.0
  image_cropper: ^1.5.1
  custom_accordion: ^1.0.0
  observe_internet_connectivity: ^1.0.2
  advance_expansion_tile: ^1.0.2
  location: ^5.0.3
  intl: ^0.19.0
  babstrap_settings_screen: ^0.1.6
  simple_connection_checker: ^0.2.1
  connectivity_plus: ^6.0.3
#  flutter_device_imei: ^0.0.2
#  mobile_device_identifier: ^0.0.2
  flutter_unique_id: ^0.0.6
  app_install_events: ^0.0.2
  external_path: ^1.0.3
  package_info_plus: ^8.0.0
  device_info_plus: ^10.1.0
#  mobile_unique_id: ^1.0.1
#  device_imei: ^0.0.4+2
#  device_information: ^0.0.4
#  flutter_device_identifier: ^0.0.1
  #  google_maps_flutter: ^2.2.8
  #  cached_network_image: ^3.3.1
  #  google_fonts: ^6.1.0
  #  internet_connection_checker_plus: ^2.3.0
  #  accordion: ^2.6.0
  #  group_radio_button: ^1.3.0
  #  async: ^2.11.0
  #  persistent_bottom_nav_bar: ^5.0.2
  #  loading_animation_widget: ^1.2.0+4
  #  sqflite_sqlcipher: ^3.0.0
  #  screenshot: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/app-icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/app/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
          weight: 100
